version: '3.7'

services:
  repairio:
    build:
      context: ./
      dockerfile: node.dockerfile
    container_name: repairio
    networks:
      - app-tier
    environment:
      MYSQL_USER: "root"
      MYSQL_PASSWORD: ""
      MYSQL_DATABASE: repairio1
      MYSQL_HOST: db
    ports:
      - "3000:3000"
      # - "80:80"
      - "5173:5173"
      - "5174:5174"
      - "443:443"
  interaction:
    build:
      context: ./
      dockerfile: interaction.dockerfile
    container_name: interaction
    networks:
      - app-tier
    ports:
      - "3001:3000"
      - "82:80"
      - "8082:8080"
  apache:
    build:
      context: ./
      dockerfile: apache.dockerfile
    container_name: apache
    networks:
      - app-tier
    ports:
      - '8081:80'
    volumes:
      - ./source/php:/usr/local/apache2/htdocs
      - ./source/php:/var/www/html

  db:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: repairio1
    volumes:
      - ./repairio1.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - app-tier
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    networks:
      - app-tier
    ports:
      - "8080:80"
networks:
  app-tier:
    driver: bridge